DBZ-6510 Use event processing failure handling mode in VitessReplicationConnection
debezium/debezium-connector-vitess pull request #138
Opened 2023-05-30 23:31 UTC by twthorn

### Summary

Use the event processing failure handling mode for handling errors appropriately in the VitessReplicationConnection. This is similar to what is done for [Postgres](https://github.com/debezium/debezium/blob/main/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java#L457). We follow the standard behaviors for error/skip/warn/ignore.

### Verification

Add a few integration tests for each branch of error/skip/warn/ignore. Check that the error throwable is set/not set appropriately. Use the example use case of an oversized grpc message to be the guaranteed failure (by setting byte max very low).

2023-06-01 09:20 UTC, jpechane requested changes
@twthorn Thanks a lot. I left two comments related to removal of unnecessary code and change in tests. The functionality itself LGTM.

2023-06-01 09:20 UTC, jpechane commented on src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
> +    public EventProcessingFailureHandlingMode getEventProcessingFailureHandlingMode() {
This should be unnecessary as `io.debezium.config.CommonConnectorConfig.EVENT_PROCESSING_FAILURE_HANDLING_MODE` declares `FAIL` as the default value.

2023-06-01 09:20 UTC, jpechane commented on src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
> +        // Since we are using the "current" as the starting position, there is a race here
This is a bit unsafe. Could you please take a look at `io.debezium.connector.mysql.StreamingSourceIT.inconsistentSchema(EventProcessingFailureHandlingMode)` to see how to intercept log messages and wait for them?

2023-06-01 20:51 UTC, twthorn commented
@jpechane Thank you for the review. I've updated with the feedback to refactor the test to wait on log messages, and to remove the unnecessary config method.

2023-06-02 04:40 UTC, merged

2023-06-02 04:40 UTC, jpechane commented
@twthorn Applied, thanks!